// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHsAzEEapwQc423PrBgd2XGOjLow6twTs',
    appId: '1:655179331422:web:2020bd443f07467ac881cf',
    messagingSenderId: '655179331422',
    projectId: 'song-gues-game',
    authDomain: 'song-gues-game.firebaseapp.com',
    storageBucket: 'song-gues-game.firebasestorage.app',
    measurementId: 'G-10H4Z4HFT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGxAWc4HqS81llCv39WGrE1Rhy8bkheo',
    appId: '1:655179331422:android:9a1c5a526b860f59c881cf',
    messagingSenderId: '655179331422',
    projectId: 'song-gues-game',
    databaseURL: 'https://song-gues-game-default-rtdb.firebaseio.com',
    storageBucket: 'song-gues-game.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvPN-vTptUZGVaGoLw_RX9105mYCrQW1o',
    appId: '1:655179331422:ios:e3d8a554d08e487cc881cf',
    messagingSenderId: '655179331422',
    projectId: 'song-gues-game',
    databaseURL: 'https://song-gues-game-default-rtdb.firebaseio.com',
    storageBucket: 'song-gues-game.firebasestorage.app',
    iosClientId: '655179331422-avpse2vcn50b12h13cqorn8u7a5bmp28.apps.googleusercontent.com',
    iosBundleId: 'com.example.songGuessGame',
  );
}
